### ISSUE TITLE
Sonata Block Bundle Edit form dont save EntityType

### ISSUE THREAD

**Issue by mesiarm** [sonata-project/SonataBlockBundle#1092]
My sonata-project/block-bundle version is 3.23.3

I´ve found Stackoverflow question same as my problem - https://stackoverflow.com/questions/51685203/sonata-block-bundle-edit-form-dont-save-entitytype 

There is accepted answer offering some workaround, but it doesn´t work for me and should work without workaround.

**Comment by VincentLanglet** [comment]
Hi.

Sorry but we don't provide support for the 3.x versions anymore.
Feel free to reopen an issue if the problem still exist with the latest version.

Also, please respect the issue template when opening an issue. :)
