### ISSUE TITLE
Remove Sonata cache

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataBlockBundle#1103]
as I can see sonata cache is not maintained anymore: https://github.com/sonata-project/cache

do you know if it's too complicated to remove this from the dependencies?

**Comment by jordisala1991** [comment]
It is already removed from 5.0, cant be completely removed from 4.x

**Comment by eerison** [comment]
But if it can removed in 4.x, why do we still require this in 4.x code?

https://github.com/sonata-project/SonataBlockBundle/blob/4.x/composer.json#L29

BC?

Edit 1: I'm saying this because there isn't any 5.x release, and I still have abandoned dependencies in my project :(

**Comment by VincentLanglet** [comment]
> But if it can removed in 4.x, why do we still require this in 4.x code?

Read again

> It is already removed from 5.0, cant be completely removed from 4.x

Remove from 5.0
CANT be remove from 4.x

> Edit 1: I'm saying this because there isn't any 5.x release, and I still have abandoned dependencies in my project :(

You can survive with the abandoned dependency which is not used.

Use dev-5.x if you really want this dependency removed.
