### ISSUE TITLE
Deprecate ContainerBlockService on 4.x

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/SonataBlockBundle#1109]
## Feature Request

That block make no sense outside AdminBundle, it needs to be deprecated and removed before 5.0

**Comment by VincentLanglet** [comment]
> That block make no sense outside AdminBundle, it needs to be deprecated and removed before 5.0

And moved to another Bundle then or just deprecated/removed ?

**Comment by jordisala1991** [comment]
it was already moved to PageBundle, here we just need deprecate + removal

**Comment by VincentLanglet** [comment]
I think I can close this seems it's not sure anymore, cf discussion on https://github.com/sonata-project/SonataBlockBundle/pull/1114
