### ISSUE TITLE
Dependency SonataCache abandoned

### ISSUE THREAD

**Issue by dmitryuk** [sonata-project/SonataBlockBundle#1110]
[SonataBlockBundle](https://github.com/sonata-project/SonataBlockBundle) requires [sonata-project/cache](https://github.com/sonata-project/SonataCacheBundle), which is anandoned. We are should to remove it from composer.json and fix a code.

**Comment by VincentLanglet** [comment]
Done in 5.x

Please look for other issues before opening one https://github.com/sonata-project/SonataBlockBundle/issues/1103
