### ISSUE TITLE
[RFC] Block Plannification 

### ISSUE THREAD

**Issue by rande** [sonata-project/SonataBlockBundle#123]
Hello

I would like to introduce a new feature in the block bundle, the ability to define a visibility range for a block.

Let's say you have an ecommerce website and some blocks might be only visible on monday between 7pm to 8pm. This feature will try to solve this.

The implementation is still not done yet, I just want some feedbacks about this feature.

ping @dbu @lsmith77

**Comment by core23** [comment]
Looks like a good idea

@dbu Can you provide a PR?

**Comment by dbu** [comment]
i am not using the SonataBlockBundle at the moment. i linked the implementation we have, i am happy to give input if somebody has time to work on it, but i don't have time to develop this.

**Comment by core23** [comment]
This issue is very old. Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
