### ISSUE TITLE
Configuration for default settings not working

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataBlockBundle#149]
For SonataDoctrinePhpcrAdmin, we usually define a tree block. We define a default setting for the `id` value. See for example https://github.com/symfony-cmf/cmf-sandbox/blob/master/app/config/config.yml#L139

This parameter is defined in the [SonataBlockBundle configuration class](https://github.com/sonata-project/SonataBlockBundle/blob/master/DependencyInjection/Configuration.php#L137). However, i can't find it being processed in the DI extension and it does not arrive at our [TreeBlockService](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Block/TreeBlockService.php)

**Comment by puffinofdoom** [comment]
Has there been any progress with this?

**Comment by dbu** [comment]
not to my knowledge.

**Comment by jordisala1991** [comment]
Maybe this PR needs to be rescued: https://github.com/sonata-project/SonataBlockBundle/pull/222
