### ISSUE TITLE
Big ugly method. Refactoring needed

### ISSUE THREAD

**Issue by spolischook** [sonata-project/SonataBlockBundle#159]
I think we have broken responsibility at Block Helper.
This class has too many dependencies - https://github.com/sonata-project/SonataBlockBundle/blob/master/Templating/Helper/BlockHelper.php#L69
One of the method (render) is so huge - https://github.com/sonata-project/SonataBlockBundle/blob/master/Templating/Helper/BlockHelper.php#L306

I propose take out some logic to separate service. In our app I create interface:
```php
<?php

namespace Sonata\BlockBundle\Cache;

interface BlockCacheManagerInterface
{
public function setBlockToCache(BlockInterface $block);
public function getBlockFromCache($blockName, array $cacheKeys);
public function getCacheService(BlockInterface $block);
}
```

Please give your response about this, that I can to pack my code in PR

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
