### ISSUE TITLE
Add Config Parameter for the BlockDatacollector

### ISSUE THREAD

**Issue by Deamon** [sonata-project/SonataBlockBundle#162]
Hi all,
As a result of the discution on this issue : https://github.com/symfony-cmf/BlockBundle/issues/192 
I would like to know if it is possible to add a parameter in the config of the block bundle to deactivate the BlockDataCollector.

By default it will be activate and if we set the parameter to false, the dataCollector would be inactive.

Would it be possible?

**Comment by core23** [comment]
Any updates for this @Deamon ?

**Comment by Deamon** [comment]
Hello @core23,
I finally use the parameter to disable the BlockDataCollector mentionned by @gonzalovilaseca on the previous issue : https://github.com/symfony-cmf/block-bundle/issues/192#issuecomment-57629411

Since disabled, I have no problem on that anymore.
