### ISSUE TITLE
[undocumented] Associating a Sonata Admin Class with a Sonata Block Service

### ISSUE THREAD

**Issue by ronanguilloux** [sonata-project/SonataBlockBundle#173]
Hi there,

It's less about an issue than it is about something I didn't find documented. Learning from the MediaBundle's `GalleryBlockService` class, I found a way to tie-in a custom block service with an admin class, giving the user a way to select a business object (a `Product`) inside a dropdown list in a custom block edition form.

![A Product Admin Class inside a Block edition form](http://media.tumblr.com/a7534cc24393efc6040092ae07ac437e/tumblr_inline_ncpuql44Jh1qhiy2f.png)

AFAIK, this wasn't documented, and [simulating an association](https://github.com/sonata-project/SonataMediaBundle/blob/master/Block/GalleryBlockService.php#L132) using a `$fieldDescription` object was the most tricky part of it.

I suppose that a [custom BlockService class example](https://gist.github.com/ronanguilloux/0676257355c3e6bf3005) (gist) may be helpfull in the documentation ?

I'm not fluent enough in english to create such a new documentation page, but I hope this may help someone a day.

**Comment by core23** [comment]
Refs https://github.com/sonata-project/SonataBlockBundle/issues/244

**Comment by jordisala1991** [comment]
Already on #244 Closing as duplicate
