### ISSUE TITLE
Method "currentAncestor" for object "Knp\Menu\MenuItem" does not exist

### ISSUE THREAD

**Issue by thundo** [sonata-project/SonataBlockBundle#174]
Hello,

I'm getting this error at sonata user profile page.

    Method "currentAncestor" for object "Knp\Menu\MenuItem" does not exist in SonataBlockBundle:Block:block_side_menu_template.html.twig at line 29

Composer relevant packages:

    sonata-project/block-bundle              2.2.13             Symfony SonataBlockBundle
    knplabs/knp-menu                         v2.0.1             An object oriented menu library
    knplabs/knp-menu-bundle                  v2.0.0             This bundle provides an integration of the KnpMenu library

Thank you

**Comment by lbrunet** [comment]
http://stackoverflow.com/questions/25793518/method-currentancestor-for-object-knp-menu-menuitem-does-not-exist-in-sonata

**Comment by rande** [comment]
fixed
