### ISSUE TITLE
BlockContentManager order to set the defaults settings

### ISSUE THREAD

**Issue by dag-io** [sonata-project/SonataBlockBundle#179]
Hello

Right now the BlockContextManager :
1. take the default settings from the config (https://github.com/sonata-project/SonataBlockBundle/blob/master/Block/BlockContextManager.php#L101)
2. take the default settings from the service (https://github.com/sonata-project/SonataBlockBundle/blob/master/Block/BlockContextManager.php#L104)

In order to override a particular block default settings in app/config.yml we would need to reverse the order so a setting set in app/config.yml have a hier priority ?

Cheers

Damien

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
