### ISSUE TITLE
Too long block id will not fit into the database

### ISSUE THREAD

**Issue by blaues0cke** [sonata-project/SonataBlockBundle#184]
When you use a too long block id (e.g. `longlongcompany.alsolongbundlename.supercoolandlongblocknamewithextranicefeatures` you will get an exception while rendering the frontend since the database is only able to store 64 characters. So after you added the block into a sonata page you will get an excetption telling you that the block `longlongcompany.alsolongbundlename.supercoolandlongblocknamewith` could not be found.

Think it would be nice when the system throws an exception when the id is too long.

**Comment by rande** [comment]
Can you open an issue to the SonataPageBundle ? Thanks

**Comment by blaues0cke** [comment]
See here: https://github.com/sonata-project/SonataPageBundle/issues/475 (hope this is what you wanted :-))

**Comment by rande** [comment]
PR is better ;)

**Comment by blaues0cke** [comment]
Hehe, yea. Will fix this when I am deep enough in the code :-)

**Comment by rande** [comment]
If I may: https://github.com/sonata-project/SonataPageBundle/blob/master/Resources/config/doctrine/BaseBlock.orm.xml#L6
