### ISSUE TITLE
no help text shown??

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataBlockBundle#193]
![bildschirmfoto 2015-04-24 um 14 34 18](https://cloud.githubusercontent.com/assets/995707/7318729/52c2f9ae-ea8f-11e4-8de9-4fbf1f01f91b.png)

![bildschirmfoto 2015-04-24 um 14 35 53](https://cloud.githubusercontent.com/assets/995707/7318730/52c3f728-ea8f-11e4-9fdd-f9fe5c48f875.png)

Why is the help text not rendered?

best
Oskar

**Comment by core23** [comment]
Have you tried ``sonata_help`` instead of ``help``?

**Comment by OskarStark** [comment]
no i didn't, but heard about that
