### ISSUE TITLE
Context Manager not supported?

### ISSUE THREAD

**Issue by MHaendel** [sonata-project/SonataBlockBundle#207]
"The options "manager", "page_id" do not exist. Known options are: "attr", "class", "code", "extra_cache_keys", "layout", "template", "ttl", "use_cache"

**Comment by Soullivaneuh** [comment]
Can you please be a bit more comprehensive?

Steps to reproduce, used code samples etc... that's the minimum to be able to help you.

Regards.

**Comment by MHaendel** [comment]
Hey, for example:

config.yml:
```yaml
sonata_block:
    context_manager: sonata.page.block.context_manager
```

**Comment by Soullivaneuh** [comment]
Your error is saying that `manager` and `page_id` key doesn't exists.

I don't think this is related to the configuration you put here neither to the bundle.

**Comment by wbloszyk** [comment]
I have the same problem. I just installed sandbox 2.4-develop. 

<code>
An exception has been thrown during the rendering of a template ("The options "manager", "page_id" do not exist. Defined options are: "attr", "class", "code", "extra_cache_keys", "layout", "template", "ttl", "use_cache".") in SonataPageBundle::layout.html.twig at line 17. 
</code>

Track:<list>
1. sonata_page_render_container('header', 'global') (SonataPageBundle TwigExtension)
2. sonata_page_render_container'    => new \Twig_Function_Method($this, 'renderContainer', ...
3. return $this->renderBlock($container, $options);
4. Sonata\BlockBundle\Templating\Helper\BlockHelper->render($block, array $options = array())
---$this->blockContextManager->get($block, $options);
5.Sonata\BlockBundle\Block\BlockContextManager->get(...)
---$settings = $this->resolve($block, array_merge($block->getSettings(), $settings));
</list>

Twig Extension from SonataPageBundle add "manager", "page_id" settings, but they missing in resolve.

**Comment by wbloszyk** [comment]
PageExtension gives options like:
array{
'use_cache' => ....
'extra_cache_keys' => array('manager' => ... , 'page_id' => ...)
'manager' => ...
'page_id' => ...
}

OptionResolver throws exception becouse is to much options.  I hope now you can repair this code :)

**Comment by rande** [comment]
@Soullivaneuh the PageBundle extends the ContextManager to add new keys.

**Comment by Soullivaneuh** [comment]
@rande is this related to https://github.com/sonata-project/SonataBlockBundle/pull/204?

**Comment by rande** [comment]
@Soullivaneuh and the fix is here: https://github.com/sonata-project/SonataPageBundle/pull/499

**Comment by Soullivaneuh** [comment]
@rande Well, I think a fix has to be done on SonataBlock if it's related to #204 because it's caused by BC breaking, isn't it?

**Comment by rande** [comment]
@Soullivaneuh the resolve method need to be more clever

**Comment by wbloszyk** [comment]
Just change config for sonata.block.templating.helper. Now sonata.block.context_manager is inject.Should be load from sonata_block configuration.

**Comment by Soullivaneuh** [comment]
Found why it's failing. I'll working on a fix right now.
