### ISSUE TITLE
Usage of MaxLength validation constraint has to be replaced with Length constraint

### ISSUE THREAD

**Issue by fredpeaks** [sonata-project/SonataBlockBundle#211]
The MaxLength validation constraint has been removed from Symfony 2.3.

In Block/Service/RssBlockService.php (line 74)  and Resources/doc/reference/your_first_block.rst (line 89), the "assertMaxLength" call should be replaced with a "assertLength" call and the "limit" option should be renammed in "max".

I think there is also an "assertMaxLength" reference in the documentation of sonata-admin.

**Comment by Soullivaneuh** [comment]
Is a Symfony deprecation? Could you provide the related link?

**Comment by fredpeaks** [comment]
If you look at the documentation of the MaxLength constraint you'll see the deprecation message:
http://symfony.com/doc/2.2/reference/constraints/MaxLength.html
