### ISSUE TITLE
sonata_block_render render an error 

### ISSUE THREAD

**Issue by houssem86** [sonata-project/SonataBlockBundle#214]
Hi,

Before, I use sonata_block_render to display my bloc without any error like this statement : 

``` twig
{{ sonata_block_render ({'name': 'xxx''}) }}
```

But, now after I install and configure sonata page in my project I have this error : 

> An exception has been thrown during the rendering of a template ("Notice: Undefined index: type") in xxxBundle: xxxx: xxxx.html.twig at line 28. 

Any solution to use my old statement to render my bloc without index type ?

**Comment by houssem86** [comment]
I created a bloc service and I added his name after index type ...

**Comment by morilog** [comment]
I have this problem too with symfony 2.7

**Comment by OskarStark** [comment]
@houssem86 does the code from @morilog works?

if yes, please let us know and close this issue!

Thank you!

**Comment by core23** [comment]
Ping @houssem86

**Comment by jordisala1991** [comment]
Without further information, this is impossible to fix (if the provided solution does not work). Closing for now. Ping me if this issue is still relevant
