### ISSUE TITLE
Block name inconsistencies

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/SonataBlockBundle#224]
In most cases the `getName` method returns an ID-like string which I guess is used for translation. But in some other cases, an English label is returned (like in NewsBundle `Recent Posts`).

Which way should it be done?

Also: do you add new strings manually to the translation files? Or you use a tool, like JMSTranslationBundle?

**Comment by OskarStark** [comment]
:+1: for new translation keys instead of English

**Comment by core23** [comment]
I think this got fixed a few months ago in the latest/dev versions. The block id should always be returned.

**Comment by core23** [comment]
This issue should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue
