### ISSUE TITLE
why does we wrote "Blocks*" instead of "Blocks" in the Profiler?

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataBlockBundle#229]
![bildschirmfoto 2015-10-05 um 13 11 31](https://cloud.githubusercontent.com/assets/995707/10337092/c7726cda-6cfd-11e5-97dc-0d3097a49d7c.png)

<img width="310" alt="bildschirmfoto 2015-10-07 um 14 12 50" src="https://cloud.githubusercontent.com/assets/995707/10337094/cb2f4852-6cfd-11e5-9cf5-c949e12fbab1.png">

can i change that @rande

**Comment by OskarStark** [comment]
Ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
That's a good question. Did you check the related code?

**Comment by OskarStark** [comment]
No, not yet, but maybe its because of the events fired

![bildschirmfoto 2015-10-14 um 11 41 49](https://cloud.githubusercontent.com/assets/995707/10480089/96cf0bd6-7268-11e5-9044-4015a8190a67.png)

**Comment by OskarStark** [comment]
If some blocks are rendered, the bubble should be green, would you like to fix this @mvhirsch ? :smile:
