### ISSUE TITLE
Encapsulate stylesheet / javascript from block

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataBlockBundle#232]
When overriding a block template, the javascript / stylesheet will still be the included. Would be better to handle this inside the template.

For example, if you have the `FeatureMediaBlockService`, the `/bundles/sonatamedia/blocks/feature_media/theme.css`will always be included also if you override the `SonataMediaBundle:Block:block_feature_media.html.twig`.

Maybe this could be handled with a custom twig node to include styles and script in the block templates?

``` twig
{% sonata_block_style "/bundles/sonatamedia/blocks/feature_media/theme.css" %}

{% sonata_block_script "/bundles/sonatamedia/blocks/feature_media/script.js" %}
```

**Comment by core23** [comment]
Maybe we could add a custom twig node to include styles and script in the block templates?
```twig
{% sonata_style "/bundles/sonatamedia/blocks/feature_media/theme.css" %}

{% sonata_script "/bundles/sonatamedia/blocks/feature_media/script.js" %}
```

**Comment by core23** [comment]
What do you think? @rande @Soullivaneuh @OskarStark Would create a new feature if wanted.

**Comment by core23** [comment]
Ping @greg0ire @OskarStark

**Comment by greg0ire** [comment]
Why / how is it still included? Is there any way to override css / js for a given block ATM? If yes why not just use that?

**Comment by core23** [comment]
The only way to override the css / js is to create a new extended block php class.

**Comment by greg0ire** [comment]
A bit cumbersome indeed. Customizing css and js from the template makes sense, I'd say go ahead with your idea it seems appropriate : you can see the entire override in one place.

**Comment by core23** [comment]
Assets are deprecated in BlockServiceInterface
