### ISSUE TITLE
Sonata_Block_Bundle  render an error.

### ISSUE THREAD

**Issue by aimeric** [sonata-project/SonataBlockBundle#255]
Hi, 

I have created a block,  my block have a service and controller. But when i refresh my page i have this error : 

```
This webpage is not available
ERR_CONNECTION_RESET
```

(My server is on and can access to my others pages)

This is my page myblock.html.twig

``` jinja
{% extends sonata_block.templates.block_base %}
{% block block %}
     {{ sonata_block_render({'type':'sonata.block.service.myblock'}) }}
{% endblock %}
```

**Comment by core23** [comment]
Can you please provide more information? Stacktrace? @aimeric

**Comment by jordisala1991** [comment]
With this we cannot help in any way, closing.
