### ISSUE TITLE
Completely Remove the OptionsResolverInterface to clean up for Symfony 3

### ISSUE THREAD

**Issue by binhle410** [sonata-project/SonataBlockBundle#260]
Currently we are using 

```
"autoload": {
    "psr-4": { "Sonata\\BlockBundle\\": "" },
    "files": ["Resources/stubs/symfony2.php"]
},
```

to simulate sym2 deprecated interface. Why don't we just remove it?

**Comment by greg0ire** [comment]
Because we support symfony2 ?

**Comment by binhle410** [comment]
so, when do we deprecate the usage of Symfony 2?

**Comment by core23** [comment]
Maybe with the 4.x release

**Comment by OskarStark** [comment]
I will close this issue, feel free to reopen it @binhle410
