### ISSUE TITLE
Travis dependencies issue on release tags

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataBlockBundle#266]
Build on 3.x is OK: https://travis-ci.org/sonata-project/SonataBlockBundle/builds/128526901

But not on 3.0.0: https://travis-ci.org/sonata-project/SonataBlockBundle/builds/128521088

This is because of the cicular dependency between admin and block bundles, but I don't know how to resolve it.

* Why this issue happen on release tag and not on 3.x?
* Maybe restore minimum stability to dev with a prefer stable option will resolve it on next release?

~~More weird: If I do a `git checkout 3.0.0` and a `composer update`, it works!~~

Edit: I can reproduce it if I follow Travis workflow: 

```bash
git clone --depth=50 --branch=3.0.0 https://github.com/sonata-project/SonataBlockBundle.git sonata-project/SonataBlockBundle
cd sonata-project/SonataBlockBundle
composer update
```

Any another ideas/suggestions? Feel free!

**Comment by Soullivaneuh** [comment]
I found something.

Seems the matching does not works with the block-bundle requirement form admin-bundle. The local composer package definition is not recognized as a 3.x release.

I fixed the `composer update` command by changing this:

```json
    "extra": {
        "branch-alias": {
            "dev-20b52266b0a4b2a70a7411f50a789b42b3c00959": "3.x-dev"
        }
    }
```

Where `20b52266b0a4b2a70a7411f50a789b42b3c00959` is the tagged commit for 3.0.0.

Maybe we could do a special thing when `TRAVIS_TAG` env var is filled by Travis.

Must be done on dev-kit.

**Comment by Soullivaneuh** [comment]
This command should solve this issue:

```bash
sed --in-place "s/\"dev-master\":/\"dev-${TRAVIS_COMMIT}\":/" composer.json
```

**Comment by Soullivaneuh** [comment]
Working! https://travis-ci.org/sonata-project/SonataBlockBundle/jobs/128667726#L218

**Comment by Soullivaneuh** [comment]
This is not the only issue.

If I push on another branch than 3.x on the repo (`travis-test`) for example, I get the same error: https://travis-ci.org/sonata-project/SonataBlockBundle/jobs/128668122#L377

We could replace the branch aliases for each travis job, but I'm not sure this is the best way to do...

@sonata-project/contributors I need your suggestions! :-)

**Comment by Soullivaneuh** [comment]
Will make it as default waiting for a better way.

**Comment by core23** [comment]
Can we close this @Soullivaneuh ?

**Comment by Soullivaneuh** [comment]
Yes but we have to keep in mind that we have to find a better way.
