### ISSUE TITLE
Fix namespace for BlockServices

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataBlockBundle#282]
I was wondering what is correct namespace for a _BlockService_?

I saw the following namespaces:
- `Vendor\AcmeBundle\Block\CustomBlockService`
- `Vendor\AcmeBundle\Block\Service\CustomBlockService`

**Comment by OskarStark** [comment]
> Vendor\AcmeBundle\Block\CustomBlockService

IMO

**Comment by Soullivaneuh** [comment]
@OskarStark According to the existing block, I would say the reverse.

`Vendor\AcmeBundle\Block\Service\CustomBlockService`

**Comment by OskarStark** [comment]
But i really don't know anything else under the `\Block\` namespace, so we have only one more, and Service is repetitive imo

**Comment by Soullivaneuh** [comment]
This is how the services are sorted. After that, if you don't want to follow this for your internal project, feel free!

It's like Symfony form namespaces...

**Comment by Soullivaneuh** [comment]
@core23 Even if you have something to request or a PR to propose related to this issue, can you please close it?

BTW, question should be avoided on GitHub issues. :+1:

**Comment by core23** [comment]
> @OskarStark According to the existing block, I would say the reverse.
Vendor\AcmeBundle\Block\Service\CustomBlockService

Sadly, that's not always the case in our bundles. That's why I put the question here and not on SO.

**Comment by OskarStark** [comment]
> Sadly, that's not always the case in our bundles. That's why I put the question here and not on SO.

OK, didn't know that, but anyway i prefer `Vendor\AcmeBundle\Block\CustomBlockService` for new ones!

**Comment by Soullivaneuh** [comment]
> Sadly, that's not always the case in our bundles. That's why I put the question here and not on SO.

Let's ping @rande for that so.

But for internal sonata project, we should follow the same name spacing...

**Comment by core23** [comment]
Please vote your prefered namespace for block services, because we use both in our bundles

👍 Vendor\AcmeBundle\ **Block** \CustomBlockService
👎 Vendor\AcmeBundle\ **Block\Service** \CustomBlockService

@sonata-project/contributors

**Comment by Soullivaneuh** [comment]
I don't think this is a matter of taste.

The base namespace is `Block\Service`, so we should follow the same for consistency AFAIK.

**Comment by greg0ire** [comment]
I think having `Service` in a namespace or class name is terrible : by that standard, be could also have `Class` namespace. Plus, a class is not really a service : a service is an object, not a class, you can have several services that use the same class.

**Comment by Soullivaneuh** [comment]
I definitely would like to have @rande opinion for this.

Maybe the namespace is like this for another reason?

**Comment by rande** [comment]
I think it should be ``Block`` for bundle, but ``Block\Service`` for the block bundle.

**Comment by Soullivaneuh** [comment]
@rande Ok. But why? :stuck_out_tongue:

**Comment by Soullivaneuh** [comment]
> I think it should be Block for bundle, but Block\Service for the block bundle.

In this case, this should be specified somewhere on the block bundle documentation to avoid confusion.

**Comment by core23** [comment]
@rande Why do you prefer multiple namespaces for `BlockServices`? Shouldn't we use the same structure for all bundles?

**Comment by core23** [comment]
Just grep'd the sonata bundles:

```
./SonataAdminBundle/Block/AdminListBlockService.php
./SonataAdminBundle/Block/AdminSearchBlockService.php
./SonataAdminBundle/Block/AdminStatsBlockService.php

./SonataBlockBundle/Block/AbstractBlockService.php
./SonataBlockBundle/Block/BaseBlockService.php
./SonataBlockBundle/Block/BlockAdminServiceInterface.php
./SonataBlockBundle/Block/BlockContext.php
./SonataBlockBundle/Block/BlockContextInterface.php
./SonataBlockBundle/Block/BlockContextManager.php
./SonataBlockBundle/Block/BlockContextManagerInterface.php
./SonataBlockBundle/Block/BlockLoaderChain.php
./SonataBlockBundle/Block/BlockLoaderInterface.php
./SonataBlockBundle/Block/BlockRenderer.php
./SonataBlockBundle/Block/BlockRendererInterface.php
./SonataBlockBundle/Block/BlockServiceInterface.php
./SonataBlockBundle/Block/BlockServiceManager.php
./SonataBlockBundle/Block/BlockServiceManagerInterface.php
./SonataBlockBundle/Block/Service/AbstractAdminBlockService.php
./SonataBlockBundle/Block/Service/AbstractBlockService.php
./SonataBlockBundle/Block/Service/AdminBlockServiceInterface.php
./SonataBlockBundle/Block/Service/BlockServiceInterface.php
./SonataBlockBundle/Block/Service/ContainerBlockService.php
./SonataBlockBundle/Block/Service/EmptyBlockService.php
./SonataBlockBundle/Block/Service/MenuBlockService.php
./SonataBlockBundle/Block/Service/RssBlockService.php
./SonataBlockBundle/Block/Service/TemplateBlockService.php
./SonataBlockBundle/Block/Service/TextBlockService.php

./SonataCommentBundle/Block/CommentThreadAsyncBlockService.php

./SonataDashboardBundle/Block/ContainerBlockService.php

./SonataDoctrineORMAdminBundle/Block/AuditBlockService.php
./SonataDoctrinePhpcrAdminBundle/Block/TreeBlockService.php

./SonataFormatterBundle/Block/FormatterBlockService.php

./SonataMediaBundle/Block/Breadcrumb/BaseGalleryBreadcrumbBlockService.php
./SonataMediaBundle/Block/Breadcrumb/GalleryIndexBreadcrumbBlockService.php
./SonataMediaBundle/Block/Breadcrumb/GalleryViewBreadcrumbBlockService.php
./SonataMediaBundle/Block/Breadcrumb/MediaViewBreadcrumbBlockService.php
./SonataMediaBundle/Block/FeatureMediaBlockService.php
./SonataMediaBundle/Block/GalleryBlockService.php
./SonataMediaBundle/Block/GalleryListBlockService.php
./SonataMediaBundle/Block/MediaBlockService.php

./SonataNewsBundle/Block/Breadcrumb/BaseNewsBreadcrumbBlockService.php
./SonataNewsBundle/Block/Breadcrumb/NewsArchiveBreadcrumbBlockService.php
./SonataNewsBundle/Block/Breadcrumb/NewsPostBreadcrumbBlockService.php
./SonataNewsBundle/Block/RecentCommentsBlockService.php
./SonataNewsBundle/Block/RecentPostsBlockService.php
./SonataPageBundle/Block/BlockContextManager.php
./SonataPageBundle/Block/BreadcrumbBlockService.php
./SonataPageBundle/Block/ChildrenPagesBlockService.php
./SonataPageBundle/Block/ContainerBlockService.php
./SonataPageBundle/Block/PageListBlockService.php
./SonataPageBundle/Block/SharedBlockBlockService.php

./SonataSeoBundle/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php
./SonataSeoBundle/Block/Breadcrumb/HomepageBreadcrumbBlockService.php
./SonataSeoBundle/Block/Social/BaseFacebookSocialPluginsBlockService.php
./SonataSeoBundle/Block/Social/BaseTwitterButtonBlockService.php
./SonataSeoBundle/Block/Social/EmailShareButtonBlockService.php
./SonataSeoBundle/Block/Social/FacebookLikeBoxBlockService.php
./SonataSeoBundle/Block/Social/FacebookLikeButtonBlockService.php
./SonataSeoBundle/Block/Social/FacebookSendButtonBlockService.php
./SonataSeoBundle/Block/Social/FacebookShareButtonBlockService.php
./SonataSeoBundle/Block/Social/PinterestPinButtonBlockService.php
./SonataSeoBundle/Block/Social/TwitterEmbedTweetBlockService.php
./SonataSeoBundle/Block/Social/TwitterFollowButtonBlockService.php
./SonataSeoBundle/Block/Social/TwitterHashtagButtonBlockService.php
./SonataSeoBundle/Block/Social/TwitterMentionButtonBlockService.php
./SonataSeoBundle/Block/Social/TwitterShareButtonBlockService.php

./SonataTimelineBundle/Block/TimelineBlock.php

./SonataTranslationBundle/Block/LocaleSwitcherBlockService.php

./SonataUserBundle/Block/AccountBlockService.php
./SonataUserBundle/Block/Breadcrumb/BaseUserProfileBreadcrumbBlockService.php
./SonataUserBundle/Block/Breadcrumb/UserIndexBreadcrumbBlockService.php
./SonataUserBundle/Block/Breadcrumb/UserProfileBreadcrumbBlockService.php
./SonataUserBundle/Block/ProfileMenuBlockService.php
```

Looks we are always using the `Block` namespace without the Service directory, except for the block bundle.

**Comment by OskarStark** [comment]
@core23 can we close this?
