### ISSUE TITLE
Console config:dump error

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/SonataBlockBundle#303]
| Question       | Answer
|----------------|-------------------------------
| BundleVersion | dev-master dbc70ca
| SymfonyVersion | v2.8.2
| PhpVersion | PHP 5.6.10

# Error message

[LogicException]                                                                           
The extension with alias "sonata_block" does not have its getConfiguration() method setup

# Steps to reproduce
config:dump SonataBlockBundle

**Comment by Soullivaneuh** [comment]
Bug confirmed.

**Comment by Soullivaneuh** [comment]
This is quite weird. Any idea of why this error?

**Comment by Soullivaneuh** [comment]
I think I found why: https://github.com/sonata-project/SonataBlockBundle/blob/3.0.0/DependencyInjection/SonataBlockExtension.php#L37-L49

The `Configuration` class of SonataBlockBundle takes `$defaultTemplates` as argument. The `getConfiguration` method try to instantiate it without any argument.

This is maybe why you have this error.

Still investigating.
