### ISSUE TITLE
Remove ugly symfony2 workaround

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataBlockBundle#313]
## Subject

Remove the ugly workaround in `composer.json`:

```json
    "autoload": {
        "files": ["Resources/stubs/symfony2.php"]
    },
```

Don't know why we have this workaround, but we should remove this or put it somewhere in the code.

**Comment by greg0ire** [comment]
> Don't know why we have this workaround, but we should remove this or put it somewhere in the code.

Don't know either, let's remove it and see if the tests pass…
