### ISSUE TITLE
Block "javascript" missing in profiler after twig updated

### ISSUE THREAD

**Issue by uLow** [sonata-project/SonataBlockBundle#361]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2.2

Hi there!
After running `composer update`, twig got update from 1.31 to 2.1, that caused error below, when running profiler:
```
“
Block "javascript" on template "@WebProfiler/Profiler/base.html.twig" does not exist.
500 Internal Server Error - Twig_Error_Runtime
”
Stack Trace
in vendor/symfony/symfony/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Profiler/base.html.twig at line 17   -
        {% endblock %}
    </head>
    <body>
        {% block body '' %}
    </body>
</html>
```

```
$ composer show sonata-project/admin-bundle
name     : sonata-project/admin-bundle
descrip. : The missing Symfony Admin Generator
keywords : Admin Generator, admin, bootstrap, sonata
versions : * 3.12.0
type     : symfony-bundle

```

https://github.com/symfony/symfony/issues/21487

**Comment by core23** [comment]
Looks like a symfony bug

**Comment by greg0ire** [comment]
@core23 they say it's on our part.

**Comment by stof** [comment]
This is not a Symfony bug. *Your* template is rendering a non-existent block (which is forbidden in Twig 2)

**Comment by greg0ire** [comment]
[Here](https://github.com/sonata-project/SonataBlockBundle/blob/b1af8138d63cc9334e5ef8c733fb824ad848c8b7/Resources/views/Profiler/block.html.twig#L116) is the offending call IMO

**Comment by core23** [comment]
Sorry for closing. I was just looking at the issue and stack trace.

**Comment by uLow** [comment]
Thank you guys for your attention and resolving this issue.

**Comment by stof** [comment]
@core23 yeah, Twig sometimes put the error on the wrong location (putting it on the block declaration in the parent template instead of putting it in the child template overriding the block)
