### ISSUE TITLE
3.3.0 throwing strange deprecation notices

### ISSUE THREAD

**Issue by mmucklo** [sonata-project/SonataBlockBundle#363]
Seeing some strange deprecation notices since updating

### Environment

dev (eng)

#### Sonata packages

```bash
 sonata-project/admin-bundle                  3.12.0            
  sonata-project/block-bundle                  3.3.0             
  sonata-project/cache                         1.0.7             
  sonata-project/core-bundle                   3.2.0             
  sonata-project/datagrid-bundle               2.2               
  sonata-project/doctrine-extensions           dev-master fbaff00
  sonata-project/doctrine-orm-admin-bundle     dev-master ab4ba73
  sonata-project/easy-extends-bundle           dev-master 36bac7e
  sonata-project/exporter                      1.7.0         
```

#### Symfony packages

```bash
  symfony/assetic-bundle                       dev-master 0241b13
  symfony/monolog-bundle                       v3.0.3            
  symfony/phpunit-bridge                       v3.2.2            
  symfony/polyfill-intl-icu                    v1.3.0            
  symfony/polyfill-mbstring                    v1.3.0            
  symfony/polyfill-php54                       v1.3.0            
  symfony/polyfill-php56                       v1.3.0            
  symfony/polyfill-php70                       v1.3.0            
  symfony/polyfill-util                        v1.3.0            
  symfony/psr-http-message-bridge              v0.3              
  symfony/security-acl                         v3.0.0            
  symfony/swiftmailer-bundle                   v2.4.2            
```

#### PHP version

```bash
$ php -v
PHP 7.0.15 (cli) (built: Feb  1 2017 01:00:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
    with Zend OPcache v7.0.15, Copyright (c) 1999-2017, by Zend Technologies```
```

## Subject
See the deprecation notices I'm seeing.

I'm not using any custom blocks at this point.

## Steps to reproduce
run phpunit on a clean cache

## Expected results
no sonata deprecation notices

## Actual results
```
Using different service id and block id is deprecated since 3.x and will be removed in 4.0: 6x
```

Coming from file: vendor/sonata-project/block-bundle/DependencyInjection/Compiler/TweakCompilerPass.php

```php
            if (strlen($arguments[0]) == 0) {
                $definition->replaceArgument(0, $id);
            } elseif ($id != $arguments[0]) {
                // NEXT_MAJOR: Remove deprecation notice
                @trigger_error(
                    'Using different service id and block id is deprecated since 3.x and will be removed in 4.0.',
                    E_USER_DEPRECATED
                );
            }
```

Potentially useful debugging information

```php
$id = "sonata.block.service.container";
$arguments = 
[ 'sonata.block.container', {Symfony\Component\DependencyInjection\Reference} [ "id" => "templating", "invalidBehavior" => 1 ]];

```

**Comment by OskarStark** [comment]
`sonata.block.service.container` != 'sonata.block.container'

**Comment by mmucklo** [comment]
@OskarStark - any clue how to fix?  There are no custom blocks and no services tagged as such as far as I can tell in the code base...

**Comment by OskarStark** [comment]
@core23 looks like we did this for the blocks, but not for the container, if I remember correct

The change was introduced here: #344

**Comment by OskarStark** [comment]
@mmucklo please check https://github.com/sonata-project/SonataBlockBundle/pull/344#issuecomment-273321084

It looks, like this behaviour is correct, isn't it @core23 ?

**Comment by mmucklo** [comment]
Saw the comment - so part of a known issue then?  Should I just wait for a fix?

**Comment by core23** [comment]
Yes, this is actual the right behavior. We can't rename the either the service name nor the block name in the stable branch, because this would end in a BC break. For now you have to live with the deprecation warnings :/

**Comment by mmucklo** [comment]
In theory that sounds great, however in practice it will cause PHPUnit to exit with a non-zero exit code, hence it can break continuous integration, unless I use one of these work arounds:

http://stackoverflow.com/questions/28850809/disable-deprecated-warning-in-symfony-2-7

**Comment by core23** [comment]
You could add a simple catch for internal blocks here: https://github.com/sonata-project/SonataBlockBundle/blob/3.x/DependencyInjection/Compiler/TweakCompilerPass.php#L43

Feel free to fix this with a PR.

**Comment by dbu** [comment]
i'll have a look

thought about already providing the service under the new name, but that would be a BC even if we make the old service name an alias - if somebody has a compiler pass, it would collide.

**Comment by greg0ire** [comment]
> if somebody has a compiler pass, it would break.

Because of a duplicate service?

**Comment by dbu** [comment]
no my idea was that we would already move the services, (and then would not trigger the deprecation) and then set up the alias for BC. but if somebody uses a compiler pass that changes one of the services, they would get an error if they do not follow the alias (which afaik does not happen automatically when doing ContainerBuilder::getDefinition). i will go with the conservative solution of not triggering the notice
