### ISSUE TITLE
Embedded blocks + multiple block of a type

### ISSUE THREAD

**Issue by Adraesh** [sonata-project/SonataBlockBundle#365]
After researching and tying to find a way to easily embedded block service and also adding multiple block from the same type into another BlockService.

I also tried to override some of the existing BlockService like FormatterBlockService or MediaBlockService without success.

Basically, I need to create several BlockService and of them is the following:

- Title1
- Content1 => wysiwyg (I can't manage to use multiple time the FormatterBlockService)
- Title2
- Content2 => wysiwyg
- Title3
- Content3 => wysiwyg

Another one is as following:

- Title
- Content => wysiwig
- Image1 => I can't manage to use multiple time the MediaBlockService
- Image2

If someone has just a quick idea it will be appreciated.

Thanks.

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
