### ISSUE TITLE
Commands.xml not exist

### ISSUE THREAD

**Issue by Chrysweel** [sonata-project/SonataBlockBundle#433]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/block-bundle    3.x-dev 7352a1f dev-master 3a30a0e Symfony SonataBlockBundle     
sonata-project/cache           2.x-dev c3c8a35 dev-master 1c365f4 Cache library
sonata-project/core-bundle     3.x-dev d02ede4 dev-master 480b92c Symfony SonataCoreBundle
sonata-project/datagrid-bundle 2.x-dev e683a7a dev-master bae1952 Symfony SonataDatagridBundle
sonata-project/intl-bundle     2.x-dev 75ce48d dev-master 5337e63 Symfony SonataIntlBundle
```
#### PHP version

```
$ php -v
PHP 7.1.1
```

## Subject

File commands.xml not exist

https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/DependencyInjection/SonataBlockExtension.php#L64

**Comment by jordisala1991** [comment]
Confirmed, this is a bug with new directory structure

**Comment by jordisala1991** [comment]
https://github.com/sonata-project/SonataBlockBundle/pull/415 this is the problem, it was merged after the directory structure migration but without taking it into account. Do you want to provide a PR @Chrysweel ?

**Comment by greg0ire** [comment]
The file exists, but is not in the right place: https://github.com/sonata-project/SonataBlockBundle/blob/3.x/Resources/config/commands.xml

**Comment by Chrysweel** [comment]
So the commands.xml must to be in correct folder I understand ?
Can I move commands.xml to src/Resources/config/commands.xml ?

**Comment by greg0ire** [comment]
for bonus points, a test using https://packagist.org/packages/matthiasnoback/symfony-dependency-injection-test would be terrific

**Comment by Chrysweel** [comment]
I do not have time now.

Maybe later.
Thanks by recommendation @greg0ire
