### ISSUE TITLE
Switch from Templating Component to Twig

### ISSUE THREAD

**Issue by covex-nn** [sonata-project/SonataBlockBundle#456]
I believe `Templating Component` will be deprecated soon, see https://github.com/symfony/symfony/pull/21035. So, i have a plan how to switch from `Templating Component` to `Twig`. The plan has 3 stages:

- [X] `Stage 1`, stable branch `3.x`: Use `Templating Component` without `templating` service and with own classes for templating.
        See https://github.com/sonata-project/SonataBlockBundle/pull/457 and https://github.com/sonata-project/dev-kit/issues/380
- [x] `Stage 2`, `master` branch: Remove usage of `Templating Component` in code, and use `Twig` directly or own classes for templating
- [x] `Stage 3`, future `master` branch: remove proxy classes for templating.

I will describe what are stages internally.

Stage 1
---

1. Add `symfony/templating` and `symfony/asset` to composer.json

2. Change all template names to Twig namespaced syntax from `BundleNameBundle:directory:filename.html.twig` to `@BundleName/directory/filename.html.twig` everywhere

3. Create new empty interface `Sonata\BlockBundle\Templating\EngineInterface` extending `Symfony\Bundle\FrameworkBundle\Templating\EngineInterface`

4. Create new empty class `Sonata\BlockBundle\Templating\TemplateLocator` extending `Symfony\Bundle\FrameworkBundle\Templating\Loader\TemplateLocator`. Create new `sonata.templating.locator` service and deprecate this new class.

5. Create class `Sonata\BlockBundle\Templating\TemplateNameParser` extending `Symfony\Bundle\FrameworkBundle\Templating`. Create new service `sonata.templating.name_parser` and deprecate this new class.

6. Create new empty class `Sonata\BlockBundle\Templating\TwigEngine` extending `Symfony\Bundle\TwigBundle\TwigEngine` implemenging new interface `Sonata\BlockBundle\Templating\EngineInterface`. Create new service `sonata.templating` with `sonata.templating.locator` and `sonata.templating.name_parser` as arguments for its constructor.

7. Change `<argument type="service" id="templating"/>` to `<argument type="service" id="sonata.templating"/>` everywhere in `src/Resources/config/*.xml`

Stage 2
---

1. Update `Sonata\BlockBundle\Templating\EngineInterface` interface: copy body from `Symfony\Bundle\FrameworkBundle\Templating\EngineInterface`, remove `extends` and deprecate.

2. Update `Sonata\BlockBundle\Templating\TwigEngine` class: copy and modify body from `Symfony\Bridge\Twig\TwigEngine`, remove all Templating Component references, remove extends and deprecate.

3. Remove `Sonata\BlockBundle\Templating\TemplateLocator` class

4. Remove `Sonata\BlockBundle\Templating\TemplateNameParser` class

5. Remove `extends` from `Sonata\BlockBundle\Templating\Helper\BlockHelper` class, remove tag `templating.helper` from service, and deprecate the class

6. Remove `symfony/templating` from composer.json

7. Remove type hint for arguments `Sonata\BlockBundle\Templating\EngineInterface` everywhere, accept both `Twig\Environment` and `Sonata\BlockBundle\Templating\EngineInterface`

8. Use `twig` service as an argument instead of `sonata.templating`

Stage 3
---

1. Set type hint where it was removed in Stage 2, accept only `Twig\Environment`

2. Remove `Sonata\BlockBundle\Templating\EngineInterface` interface

3. Remove `Sonata\BlockBundle\Templating\Helper\BlockHelper` class

4. Remove `Sonata\BlockBundle\Templating\TwigEngine` class

What do you think?

**Comment by greg0ire** [comment]
Great work! One question : how can people avoid deprecations introduced in stage 1?

**Comment by covex-nn** [comment]
@greg0ire deprecations will be only in comments, without trigger_error, these classes were created just for a case if parent classes will be unavailable when templating extension is not activated in `framework`. See [TemplateLocator.php](https://github.com/covex-nn/SonataBlockBundle/blob/twig/src/Templating/TemplateLocator.php) or [TemplateNameParser.php](https://github.com/covex-nn/SonataBlockBundle/blob/twig/src/Templating/TemplateNameParser.php) - deprecation is just a "flag"

**Comment by greg0ire** [comment]
OK great !

**Comment by covex-nn** [comment]
A list of `sonata-project` bundles, where we should switch from `templating` to `sonata.templating` service and paths to templates should use twig namespaced syntax before Stage 2:

* https://github.com/sonata-project/SonataAdminBundle
* https://github.com/sonata-project/SonataClassificationBundle
* https://github.com/sonata-project/SonataCommentBundle
* https://github.com/sonata-project/SonataDashboardBundle
* https://github.com/sonata-project/SonataDoctrineORMAdminBundle
* https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle
* https://github.com/sonata-project/SonataFormatterBundle
* https://github.com/sonata-project/SonataMediaBundle
* https://github.com/sonata-project/SonataNewsBundle
* https://github.com/sonata-project/SonataPageBundle
* https://github.com/sonata-project/SonataSeoBundle
* https://github.com/sonata-project/SonataTimelineBundle
* https://github.com/sonata-project/SonataTranslationBundle

**Comment by core23** [comment]
Can you create a `dev-kit` issue with a checklist please @covex-nn ?

**Comment by covex-nn** [comment]
@core23 unfortunately i do not know what is "`dev-kit` issue" =(

Did you mean issue in https://github.com/sonata-project/dev-kit/ ? After merge and release #457 i planned to create PR "[WIP] Stage 2" here, in SonataBlockBundle repository, with a checklist (and to remove [WIP] prefix after all checks)

**Comment by greg0ire** [comment]
Yes that's exactly it

**Comment by covex-nn** [comment]
@core23 @greg0ire done =)

**Comment by jordisala1991** [comment]
@covex-nn can this issue be closed? this bundle is completed right?

**Comment by covex-nn** [comment]
Yes, this issue can be closed
