### ISSUE TITLE
[RFC] Use class name instead of service id

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataBlockBundle#499]
Symfony is getting rid of service ids, so we should also remove them.

ATM we use some magic in the [TweakCompilerPass](https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/DependencyInjection/Compiler/TweakCompilerPass.php#L41-L58) to auto inject the service id into BlockServices as block name. This is the prefered way for the next major release of the BlockBundle. 

IMHO we should use an other solution: the class name. We should deprecate the `BlockServiceInterface::getName` method and use the class name and pass it to the translator when displaying the block name.

**Comment by core23** [comment]
Maybe use `StringUtil::fqcnToBlockPrefix(\get_class($this));` for service ids?

**Comment by core23** [comment]
So, if the change the display name / translation key will this be a BC break or can we do this on the stable branch?

**Comment by kunicmarko20** [comment]
not sure, technically app won't break, only the translations would be gone

**Comment by core23** [comment]
We don't need this, as we remove the `getName` method here: #578
