### ISSUE TITLE
Support Block Annotations

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataBlockBundle#511]
## Feature Request

It would be great if you can define a block or a breadcrumb via annotations. So you don't need any specific mapping or definition.

**Comment by kunicmarko20** [comment]
Maybe I can make this part of my Bundle?

**Comment by core23** [comment]
There is already an annotation for blocks: https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/Annotation/Block.php

Can you try to support both JmsDI and Doctrine inside this bundle @kunicmarko20 ?

(Same for the AdminBundle)

**Comment by kunicmarko20** [comment]
Not really interested in JmsDI, never used it and never plan to.

**Comment by core23** [comment]
Not needed. This can be done using normal service discovery
https://symfony.com/blog/new-in-symfony-3-3-psr-4-based-service-discovery
