### ISSUE TITLE
Remove implicit dependency against SonataAdminBundle

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataBlockBundle#585]
## Feature Request
Remove implicit dependency against SonataAdminBundle by removing all the usages of classes provided by `Sonata\AdminBundle\` namespace.

This is a follow up of sonata-project/SonataAdminBundle#5622.

https://github.com/sonata-project/SonataBlockBundle/blob/d0a67fcd6873e234467cd58b35aa3feb5b54a6ff/src/Block/Service/AbstractAdminBlockService.php#L16
https://github.com/sonata-project/SonataBlockBundle/blob/d0a67fcd6873e234467cd58b35aa3feb5b54a6ff/src/Event/TextBlockListener.php#L16

### To do
* Declarations of `Sonata\AdminBundle\Form\FormMapper` must be replaced with `Sonata\BlockBundle\Form\Mapper\FormMapper`;
* Find a replacement or a way to avoid the usage of `Sonata\AdminBundle\Admin\AdminInterface`.

**Comment by core23** [comment]
Already done on the master branch
