### ISSUE TITLE
CategoriesMenuBlockService - Variable "macros" does not exist.

### ISSUE THREAD

**Issue by salamichel** [sonata-project/SonataBlockBundle#637]
ProductBundle/Block/CategoriesMenuBlockService use 

'menu_template' => '@SonataBlock/Block/block_side_menu_template.html.twig',     

Variable "macros" does not exist.

#### Sonata packages
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.54.0             = 3.54.0
sonata-project/block-bundle              3.18.1             = 3.18.1
sonata-project/cache                     2.0.1              = 2.0.1
sonata-project/classification-bundle     3.9.0              = 3.9.0
sonata-project/comment-bundle            3.1.1              = 3.1.1
sonata-project/core-bundle               3.17.0             = 3.17.0
sonata-project/datagrid-bundle           2.5.0              ~ 3.0.0
sonata-project/doctrine-extensions       1.3.1              = 1.3.1
sonata-project/doctrine-orm-admin-bundle 3.10.0             = 3.10.0
sonata-project/easy-extends-bundle       2.5.0              = 2.5.0
sonata-project/ecommerce                 dev-master 46711cf = dev-master 46711cf
sonata-project/exporter                  2.0.1              = 2.0.1
sonata-project/formatter-bundle          4.1.3              = 4.1.3
sonata-project/intl-bundle               2.7.0              = 2.7.0
sonata-project/media-bundle              3.20.1             = 3.20.1
sonata-project/media-orm-pack            1.0.0              = 1.0.0
sonata-project/notification-bundle       3.6.2              = 3.6.2
sonata-project/seo-bundle                2.7.0              = 2.7.0
sonata-project/timeline-bundle           3.4.0              = 3.4.0
sonata-project/user-bundle               4.5.0              = 4.5.0

#### Symfony packages
$ composer show --latest 'symfony/*'
Restricting packages listed in "symfony/symfony" to "4.3.*"
symfony/apache-pack                v1.0.1  = v1.0.1  A pack for Apache supp...
symfony/asset                      v4.3.4  = v4.3.4  Symfony Asset Component
symfony/cache                      v4.3.4  = v4.3.4  Symfony Cache componen...
symfony/cache-contracts            v1.1.5  = v1.1.5  Generic abstractions r...
symfony/config                     v4.3.4  = v4.3.4  Symfony Config Component
symfony/console                    v4.3.4  = v4.3.4  Symfony Console Component
symfony/debug                      v4.3.4  = v4.3.4  Symfony Debug Component
symfony/dependency-injection       v4.3.4  = v4.3.4  Symfony DependencyInje...
symfony/doctrine-bridge            v4.3.4  = v4.3.4  Symfony Doctrine Bridge
symfony/dotenv                     v4.3.4  = v4.3.4  Registers environment ...
symfony/event-dispatcher           v4.3.4  = v4.3.4  Symfony EventDispatche...
symfony/event-dispatcher-contracts v1.1.5  = v1.1.5  Generic abstractions r...
symfony/expression-language        v4.3.4  = v4.3.4  Symfony ExpressionLang...
symfony/filesystem                 v4.3.4  = v4.3.4  Symfony Filesystem Com...
symfony/finder                     v4.3.4  = v4.3.4  Symfony Finder Component
symfony/flex                       v1.4.6  = v1.4.6  Composer plugin for Sy...
symfony/form                       v4.3.4  = v4.3.4  Symfony Form Component
symfony/framework-bundle           v4.3.4  = v4.3.4  Symfony FrameworkBundle
symfony/http-foundation            v4.3.4  = v4.3.4  Symfony HttpFoundation...
symfony/http-kernel                v4.3.4  = v4.3.4  Symfony HttpKernel Com...
symfony/inflector                  v4.3.4  = v4.3.4  Symfony Inflector Comp...
symfony/intl                       v4.3.4  = v4.3.4  A PHP replacement laye...
symfony/maker-bundle               v1.13.0 = v1.13.0 Symfony Maker helps yo...
symfony/mime                       v4.3.4  = v4.3.4  A library to manipulat...
symfony/monolog-bridge             v4.3.4  = v4.3.4  Symfony Monolog Bridge
symfony/monolog-bundle             v3.4.0  = v3.4.0  Symfony MonologBundle
symfony/options-resolver           v4.3.4  = v4.3.4  Symfony OptionsResolve...
symfony/polyfill-intl-icu          v1.12.0 = v1.12.0 Symfony polyfill for i...
symfony/polyfill-intl-idn          v1.12.0 = v1.12.0 Symfony polyfill for i...
symfony/polyfill-mbstring          v1.12.0 = v1.12.0 Symfony polyfill for t...
symfony/polyfill-php72             v1.12.0 = v1.12.0 Symfony polyfill backp...
symfony/polyfill-php73             v1.12.0 = v1.12.0 Symfony polyfill backp...
symfony/process                    v4.3.4  = v4.3.4  Symfony Process Component
symfony/profiler-pack              v1.0.4  = v1.0.4  A pack for the Symfony...
symfony/property-access            v4.3.4  = v4.3.4  Symfony PropertyAccess...
symfony/property-info              v4.3.4  = v4.3.4  Symfony Property Info ...
symfony/routing                    v4.3.4  = v4.3.4  Symfony Routing Component
symfony/security-acl               v3.0.2  = v3.0.2  Symfony Security Compo...
symfony/security-bundle            v4.3.4  = v4.3.4  Symfony SecurityBundle
symfony/security-core              v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/security-csrf              v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/security-guard             v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/security-http              v4.3.4  = v4.3.4  Symfony Security Compo...
symfony/service-contracts          v1.1.6  = v1.1.6  Generic abstractions r...
symfony/stopwatch                  v4.3.4  = v4.3.4  Symfony Stopwatch Comp...
symfony/swiftmailer-bundle         v3.2.8  = v3.2.8  Symfony SwiftmailerBundle
symfony/templating                 v4.3.4  = v4.3.4  Symfony Templating Com...
symfony/translation                v4.3.4  = v4.3.4  Symfony Translation Co...
symfony/translation-contracts      v1.1.6  = v1.1.6  Generic abstractions r...
symfony/twig-bridge                v4.3.4  = v4.3.4  Symfony Twig Bridge
symfony/twig-bundle                v4.3.4  = v4.3.4  Symfony TwigBundle
symfony/validator                  v4.3.4  = v4.3.4  Symfony Validator Comp...
symfony/var-dumper                 v4.3.4  = v4.3.4  Symfony mechanism for ...
symfony/var-exporter               v4.3.4  = v4.3.4  A blend of var_export(...
symfony/web-profiler-bundle        v4.3.4  = v4.3.4  Symfony WebProfilerBundle
symfony/web-server-bundle          v4.3.4  = v4.3.4  Symfony WebServerBundle
symfony/yaml                       v4.3.4  = v4.3.4  Symfony Yaml Component

#### PHP version
$ php -v
PHP 7.2.18 (cli) (built: Apr 30 2019 23:32:39) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

## Subject
I'm trying to install Sonata Ecommerce on Sf 4.1. I'm facing many bugs. here 

## Steps to reproduce
Install Sonata Ecommerce branch Master. Create product to dedicated category and collection then go to front page "/shop/catalog/" route : sonata_catalog_index

## Expected results
Get Knp Menu of categories

## Actual results

Twig\Error\
RuntimeError
in \vendor/sonata-project/block-bundle/src/Resources/views/Block/block_side_menu_template.html.twig (line 57)
        {%- set listAttributes = item.childrenAttributes|merge({'class': childrenClasses|join(' ') }) %}        {{ block('list') }}    {% endif %}{% endblock %}{% block linkElement %}<a href="{{ item.uri }}"{{ macros.attributes(item.attributes|merge(item.linkAttributes)|merge(attributes)) }}>{{ block('label') }}</a>{% endblock %}{% block spanElement %}<div{{ macros.attributes(item.attributes|merge(item.labelAttributes)|merge(attributes)) }}><h4 class="list-group-item-heading">{{ block('label') }}</h4></div>{% endblock %}

**Comment by OskarStark** [comment]
Which twig version are you using?

**Comment by salamichel** [comment]
@OskarStark I'm using twig 2.12
```
$ composer info twig/*
twig/extensions v1.5.4  Common additional features for Twig that do not directly belong in core
twig/twig       v2.12.0 Twig, the flexible, fast, and secure template language for PHP


```
