### ISSUE TITLE
Create `UPGRADE-4.0.md`

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataBlockBundle#661]
## Feature Request

Create `UPGRADE-4.0.md` file to document the changes required to upgrade to version 4.

**Comment by greg0ire** [comment]
Woops, looks like I forgot that!

**Comment by greg0ire** [comment]
Wait no actually it does exist, the wrong thing is the default branch still being 4.x

**Comment by phansys** [comment]
I didn't noticed that. Thank you!

**Comment by greg0ire** [comment]
This is probably due to https://github.com/sonata-project/dev-kit/pull/523 not being merged
