### ISSUE TITLE
Can't install block bundle on symfony 4.3

### ISSUE THREAD

**Issue by tonyellow** [sonata-project/SonataBlockBundle#669]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.56.1 3.56.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.18.2 4.1.0  Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.17.2 3.17.2 Symfony SonataCoreBundle (abandoned)
sonata-project/datagrid-bundle           2.5.0  3.0.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.5.1  1.5.1  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.12.0 3.12.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library
sonata-project/google-authenticator      2.2.0  2.2.0  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.7.0  2.7.0  Symfony SonataIntlBundle
sonata-project/translation-bundle        2.4.2  2.4.2  SonataTranslationBundle
sonata-project/user-bundle               4.5.1  4.5.1  Symfony SonataUserBundle```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/asset                      v4.3.9  v4.3.9  Symfony Asset Component
symfony/cache                      v4.3.9  v4.3.9  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v1.1.7  v2.0.1  Generic abstractions related to caching
symfony/config                     v4.3.9  v4.3.9  Symfony Config Component
symfony/console                    v4.3.9  v4.3.9  Symfony Console Component
symfony/debug                      v4.3.9  v4.3.9  Symfony Debug Component
symfony/dependency-injection       v4.3.9  v4.3.9  Symfony DependencyInjection Component
symfony/doctrine-bridge            v4.3.9  v4.3.9  Symfony Doctrine Bridge
symfony/dotenv                     v4.3.9  v4.3.9  Registers environment variables from a .env file
symfony/event-dispatcher           v4.3.9  v4.3.9  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.7  v2.0.1  Generic abstractions related to dispatching event
symfony/expression-language        v4.3.9  v4.3.9  Symfony ExpressionLanguage Component
symfony/filesystem                 v4.3.9  v4.3.9  Symfony Filesystem Component
symfony/finder                     v4.3.9  v4.3.9  Symfony Finder Component
symfony/flex                       v1.6.0  v1.6.0  Composer plugin for Symfony
symfony/form                       v4.3.9  v4.3.9  Symfony Form Component
symfony/framework-bundle           v4.3.9  v4.3.9  Symfony FrameworkBundle
symfony/http-client                v4.3.9  v4.3.9  Symfony HttpClient component
symfony/http-client-contracts      v1.1.8  v2.0.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.3.9  v4.3.9  Symfony HttpFoundation Component
symfony/http-kernel                v4.3.9  v4.3.9  Symfony HttpKernel Component
symfony/inflector                  v4.3.9  v4.3.9  Symfony Inflector Component
symfony/intl                       v4.3.9  v4.3.9  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle               v1.14.3 v1.14.3 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mercure                    v0.3.0  v0.3.0  Symfony Mercure Component
symfony/mercure-bundle             0.2.3   0.2.3   Symfony MercureBundle
symfony/mime                       v4.3.9  v4.3.9  A library to manipulate MIME messages
symfony/options-resolver           v4.3.9  v4.3.9  Symfony OptionsResolver Component
symfony/polyfill-intl-icu          v1.13.1 v1.13.1 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.13.1 v1.13.1 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring          v1.13.1 v1.13.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.13.1 v1.13.1 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.13.1 v1.13.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                    v4.3.9  v4.3.9  Symfony Process Component
symfony/profiler-pack              v1.0.4  v1.0.4  A pack for the Symfony web profiler
symfony/property-access            v4.3.9  v4.3.9  Symfony PropertyAccess Component
symfony/property-info              v4.3.9  v4.3.9  Symfony Property Info Component
symfony/routing                    v4.3.9  v4.3.9  Symfony Routing Component
symfony/security-acl               v3.0.4  v3.0.4  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.3.9  v4.3.9  Symfony SecurityBundle
symfony/security-core              v4.3.9  v4.3.9  Symfony Security Component - Core Library
symfony/security-csrf              v4.3.9  v4.3.9  Symfony Security Component - CSRF Library
symfony/security-guard             v4.3.9  v4.3.9  Symfony Security Component - Guard
symfony/security-http              v4.3.9  v4.3.9  Symfony Security Component - HTTP Integration
symfony/serializer                 v4.3.9  v4.3.9  Symfony Serializer Component
symfony/service-contracts          v1.1.8  v2.0.1  Generic abstractions related to writing services
symfony/stopwatch                  v4.3.9  v4.3.9  Symfony Stopwatch Component
symfony/swiftmailer-bundle         v3.4.0  v3.4.0  Symfony SwiftmailerBundle
symfony/templating                 v4.3.9  v4.3.9  Symfony Templating Component
symfony/translation                v4.3.9  v4.3.9  Symfony Translation Component
symfony/translation-contracts      v1.1.7  v2.0.1  Generic abstractions related to translation
symfony/twig-bridge                v4.3.9  v4.3.9  Symfony Twig Bridge
symfony/twig-bundle                v4.3.9  v4.3.9  Symfony TwigBundle
symfony/validator                  v4.3.9  v4.3.9  Symfony Validator Component
symfony/var-dumper                 v4.3.9  v4.3.9  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v4.3.9  v4.3.9  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                   v4.3.9  v4.3.9  Symfony WebLink Component
symfony/web-profiler-bundle        v4.3.9  v4.3.9  Symfony WebProfilerBundle
symfony/workflow                   v4.3.9  v4.3.9  Symfony Workflow Component
symfony/yaml                       v4.3.9  v4.3.9  Symfony Yaml Component```

## Subject

I'm trying to install the block bundle in my installation but it is generating an error. This is the composer command: composer require sonata-project/block-bundle

## Expected results
Installation of the block bundle.

## Actual results
MacBook-Pro:api anthony$ docker-compose exec php composer require sonata-project/block-bundle
Using version ^4.1 for sonata-project/block-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/admin-bundle 3.56.1 requires sonata-project/block-bundle ^3.17 -> satisfiable by sonata-project/block-bundle[3.17.0, 3.18.0, 3.18.1, 3.18.2, 3.x-dev] but these conflict with your requirements or minimum-stability.
    - sonata-project/admin-bundle 3.56.1 requires sonata-project/block-bundle ^3.17 -> satisfiable by sonata-project/block-bundle[3.17.0, 3.18.0, 3.18.1, 3.18.2, 3.x-dev] but these conflict with your requirements or minimum-stability.
    - sonata-project/admin-bundle 3.56.1 requires sonata-project/block-bundle ^3.17 -> satisfiable by sonata-project/block-bundle[3.17.0, 3.18.0, 3.18.1, 3.18.2, 3.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for sonata-project/admin-bundle (locked at 3.56.1, required as ^3.56) -> satisfiable by sonata-project/admin-bundle[3.56.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by kniziol** [comment]
@tonyellow 
As you see in details of https://packagist.org/packages/sonata-project/admin-bundle package, `sonata-project/block-bundle` is required.

You are trying to install `sonata-project/block-bundle`, but it is already installed:
```
$ composer show --latest 'sonata-project/*'
(...)
sonata-project/block-bundle              3.18.2 4.1.0  Symfony SonataBlockBundle
```
So, why are trying to install package that is installed?

**Comment by cloudcanyon** [comment]
Can you show your composer.json? I guess sonata-project/admin-bundle is locked at 3.56.1 and you (or rather composer) try to install sonata-project/block-bundle:^4.1, so it cannot be done.

1. sonata-project/admin-bundle is in your project already, as mentioned above.
2. Fix your version in composer.json (sonata-project/admin-bundle forced to 3.56.1).

I'm 99% sure there is something wrong in your composer.json and required versions for any packages - if you could copy them here.

**Comment by kfrankiewicz** [comment]
Can you show your composer.json? I guess sonata-project/admin-bundle is locked at 3.56.1 and you (or rather composer) try to install sonata-project/block-bundle:^4.1, so it cannot be done.

    sonata-project/admin-bundle is in your project already, as mentioned above.
    Fix your version in composer.json (sonata-project/admin-bundle forced to 3.56.1).

I'm 99% sure there is something wrong in your composer.json and required versions for any packages - if you could copy them here.

**Comment by wbloszyk** [comment]
@tonyellow You can not install 'sonata-project/block-bundle 4.x' with 'sonata-project/admin-bundle'. Use 3.x instead. 

^3.17 means u can install >= 3.17 and < 4.0 version.

**Comment by VincentLanglet** [comment]
sonata-project/block-bundle 3 is already installed, and sonata-project/block-bundle 4 is not compatible with sonataAdminBundle ATM.
