### ISSUE TITLE
Upgrade block-bundle to 4.x in sonata-project bundles

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataBlockBundle#700]
## Feature Request
After watching some issue with Blocks (https://github.com/sonata-project/SonataMediaBundle/pull/1737, https://github.com/sonata-project/SonataMediaBundle/pull/1732) I came up with an idea.

All sonata-project stable bundles(Sonata 3) using `block-bundle 3.x` but 4.x is released. 

### block-bundle 4.0 upgrade change:

1. block constructor 
1. `AbstractAdminBlockService/AdminBlockServiceInterface` to `EditableBlockService`
1. Return type hints
1. Conflict with CoreBundle

### Resolve something like: (I will add example son - PR for SonataNewsBundle)

1. https://github.com/sonata-project/SonataClassificationBundle/pull/488
1. some steps needed 
    - remove  `AbstractAdminBlockService/AdminBlockServiceInterface` implementations
    - add methods from `AbstractAdminBlockService`
    - add methods from `EditableBlockServce`
    - methods from `EditableBlockServie` should not call `Abstra...` methods and vice versa
    - some check for override methods should be add
1. I will describe it below
1. Resolve conflict with CoreBundle 
    - https://github.com/sonata-project/SonataCoreBundle/issues/739
    - new realease of BlockBundle 4.x will be required (to allow use 0.x extensions)
    - or user can install extensions 0.x as 1.x

### Return type hints return type hints
1. move Block directory to Model/Block
1. Create the same Class in Block like in example: 
```php 
if (`SonataBlockBundle3`) {
    class SomeBlockService Extends Modal/Block/SomeBlockServie {}  
} elseif (`SonataBlockBundle4`) {
    // extends the came thing like Modal/Block/SomeBlockServie
    // we can add `EditableBlockService` becouse user make block-bundle MAJOR UPDATE
    class SomeBlockService Extends AbstractBlockService implements EditableBlockService
    {
        /**
        * var Modal/Block/SomeBlockServie
        */
        private $blockService;

        public function __construct($env, $someService)
        {
              $this->blockService = new Modal/Block/SomeBlockServie($env, $someService),
        }

        // add return type hints 
        public function configureSettings(OptionsResolver $resolver): void
        {
              $this->blockService->configureSettings($resolver);
        }
        .... // for all extended methods
    }  
}
```
## Before start - resolve conflict with CoreBundle: 
- [x] https://github.com/sonata-project/SonataCoreBundle/issues/739
- [x] add support for extensions 0.x to block-bundle 4.x to resolve core-bundle conflict

## TODO: 
- [ ] sandbox
- [ ] ecommerce
- [ ] SonataAdminBundle
- [ ] SonataClassificationBundle
- [ ] SonataCommentBundle
- [ ] SonataDashboardBundle
- [ ] SonataDoctrineORMAdminBundle
- [ ] SonataDoctrinePhpcrAdminBundle
- [ ] SonataFormatterBundle
- [ ] SonataMediaBundle
- [ ] SonataNewsBundle
- [ ] SonataPageBundle
- [ ] SonataSeoBundle
- [ ] SonataTimelineBundle
- [ ] SonataTranslationBundle ??

**Comment by jorrit** [comment]
I think before ' add support for extensions 0.x to block-bundle 4.x to resolve core-bundle conflict' can be implemented, sonata-project/form-extensions needs to support Symfony 5. Otherwise the Symfony 5 compatibility of block-bundle 4.x is undone.

**Comment by wbloszyk** [comment]
@jorrit CoreBundle is almost dropped in Sonata 3 and should not be support in Sonata 4 (as extensions 0.x). More info here:
https://github.com/sonata-project/dev-kit/issues/697

I should update this issue becouse some things are changed.

**Comment by jorrit** [comment]
If that is the case, is it even a goal to support Symfony 5 in Sonata 3?

**Comment by wbloszyk** [comment]
The goal for me now is drop all deprecated bundles and make stable sandbox 3.0 based on Symfony4.4 and Sonata 3.

IMHO sonata-project team is more focus on realease AdminBundle 4 now. Anyway I will help if it will be possible.

**Comment by wbloszyk** [comment]
Close in favor for https://github.com/sonata-project/dev-kit/issues/785
