### ISSUE TITLE
Return only string in BlockContextInterface::getTemplate

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataBlockBundle#855]
## Feature Request

Ref: https://github.com/sonata-project/SonataBlockBundle/pull/776

I don't know for sure if `getTemplate` should always return a `string`, this is just a reminder to take a look at this for  `5.x`.

**Comment by VincentLanglet** [comment]
@core23 I believe you use/used a lot the blockBundle features. Do it make sens to you that `getTemplate` returns null or should we restrict it to string ?

**Comment by core23** [comment]
The `getTemplate` method is used on every block service, so the method should return a `string` value of throw an exception.

**Comment by VincentLanglet** [comment]
So we should enforce the construct to have a template provided in the settings too then.
