### ISSUE TITLE
BlockBundle navigation menu is incorrectly duplicated to TimelineBundle navigation menu

### ISSUE THREAD

**Issue by vlad-ghita** [sonata-project/SonataBlockBundle#881]
On the left, I'm vewing documentation for BlockBundle.
On the right, I'm vewing documentation for TimelineBundle.

TimelineBundle is completely missing navigation menu.
Perhaps it's a different bug; I don't know.

![missing_menus_for_timeline_bundle___duplicate_menus_for_block_bundle](https://user-images.githubusercontent.com/422623/116858194-a6041a00-ac06-11eb-83a9-f55e488a13a9.png)

**Comment by jordisala1991** [comment]
Docs are moved away from the website, so this won't be a problem anymore.
